Auction Refactoring 및 Product 시작가 추가
11-itsmine/itsmine pull request #73
Opened 2024-07-26 10:32 UTC by xv1226

## #️⃣ 연관된 이슈

> ex) #이슈번호, #이슈번호
#67 #68 

## 📝 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

리팩토링 및 시작가 추가,연관관계 구현

### 스크린샷 (선택)

## 💬 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

2024-07-26 10:47 UTC, seongchankim1 requested changes

2024-07-26 10:47 UTC, seongchankim1 commented on src/main/java/com/sparta/itsmine/domain/auction/contoller/AuctionController.java
> +                responseDto.getStatus().equals(ProductStatus.SUCCESS_BID) ? AUCTION_SUCCESSFUL_BID
BAD_REQUEST의 경우에도 잘 작동하나요?

2024-07-26 10:47 UTC, seongchankim1 commented on src/main/java/com/sparta/itsmine/domain/auction/entity/Auction.java
> +        if (bidPrice < product.getCurrentPrice()
작거나 같은 <= 값으로 해야할 것 같습니다!

2024-07-26 11:08 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/entity/Auction.java
> +        if (bidPrice < product.getCurrentPrice()
고쳐서 다시 올리겠습니다

2024-07-26 11:10 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/contoller/AuctionController.java
> +                responseDto.getStatus().equals(ProductStatus.SUCCESS_BID) ? AUCTION_SUCCESSFUL_BID
예 잘 동작합니다

2024-07-26 11:12 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/entity/Auction.java
> +        if (bidPrice < product.getCurrentPrice()
고쳤습니다 알려주셔서 감사합니다

2024-07-26 11:26 UTC, seongchankim1 approved these changes

2024-07-29 11:03 UTC, leebeanbin commented on src/main/java/com/sparta/itsmine/domain/auction/service/AuctionService.java
> +    public Product getProduct(Long productId) {
이 부분은 ProductAdapter를 사용하셔서 가져오셔도 될 것 같아요

ProductAdapter adapter;
adapter.getProduct(productId);

이렇게 사용하시면 될 것 같아요 안에 정의해놓았습니다.

2024-07-29 13:07 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/service/AuctionService.java
> +    public Product getProduct(Long productId) {
public Product getProduct(Long productId) {
       return productAdapter.getProduct(productId);
    }
    
    이런 식으로 리팩토링 했습니다

2024-07-30 02:41 UTC, leebeanbin commented on src/main/java/com/sparta/itsmine/domain/auction/service/AuctionService.java
> +    public Product getProduct(Long productId) {
굳이 메서드를 만들지 않고 그냥 가져와서 사용해도 무방할거 같아요!

2024-07-30 02:43 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/service/AuctionService.java
> +    public Product getProduct(Long productId) {
예 알겠습니다 그럼 그렇게 하겠습니다

2024-07-30 02:47 UTC, xv1226 commented on src/main/java/com/sparta/itsmine/domain/auction/service/AuctionService.java
> +    public Product getProduct(Long productId) {
productAdapter.getProduct로 getProduct 메소드 대체 완료했습니다

2024-07-30 02:47 UTC, leebeanbin approved these changes
수정이 완료가 되면 머지해주세요!
제가 마지막으로 상품 상태 saved 지우고 바로 마감기한 등록하는 로직으로 수정할게요

2024-07-30 02:47 UTC, merged